### ISSUE TITLE
关于类别损失计算的问题

### ISSUE THREAD

**Issue by whalefa1I** [yyccR/yolov5_in_tf2_keras#3]
您好，loss这段不是很理解，
https://github.com/yyccR/yolov5_in_tf2_keras/blob/3e6645cbf94d2a1e11c33663e80113daa4590321/loss.py#L142-L152
请问targets最后两位应该是置信度1和最佳的anchor索引吗？
https://github.com/yyccR/yolov5_in_tf2_keras/blob/3e6645cbf94d2a1e11c33663e80113daa4590321/loss.py#L288-L293
那这边split出来的true_obj, true_cls应该就是对应的置信度1和最佳的anchor索引吧。
那这个类别损失
https://github.com/yyccR/yolov5_in_tf2_keras/blob/3e6645cbf94d2a1e11c33663e80113daa4590321/loss.py#L356
计算的不是最佳anchor索引吗，是跟obj_mask 有关系吗

**Comment by whalefa1I** [comment]
啊不好意思好像是这个sparse_categorical_crossentropy损失函数，没看到

**Comment by yyccR** [comment]
好的，我刚打开代码想看看是不是写错了, -.-

**Comment by whalefa1I** [comment]
但是好像没地方和true_cls做loss哎，麻烦您还是帮我看看好了嘻嘻

**Comment by yyccR** [comment]
在compute_loss的__call__方法里面，不是有pred_cls吗，就是拿那个跟true_cls做损失的

**Comment by whalefa1I** [comment]
傻了傻了，把4看成5了，以为填进去的是best_anchor_index，实际是class。
